# Generated by Django 2.2.4 on 2019-09-02 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeOfUser',
            field=models.CharField(choices=[('admin', 'admin'), ('dda', 'dda'), ('ado', 'ado')], default='admin', max_length=10),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('block_name', models.CharField(max_length=50)),
                ('village_name', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('acq_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('acq_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('typeofChoice', models.CharField(choices=[('pending', 'pending'), ('ongoing', 'ongoing'), ('completed', 'completed')], default='pending', max_length=10)),
                ('ado', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ado', to='api.User')),
                ('ddo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ddo', to='api.User')),
            ],
        ),
    ]
