# Generated by Django 2.2.4 on 2019-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoreport',
            name='flag',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('stop', 'Stop')], max_length=50, null=True),
        ),
    ]
