# Generated by Django 2.2.4 on 2019-09-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adoreport_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_district', to='api.District'),
        ),
    ]
