# Generated by Django 2.2.4 on 2019-09-03 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190902_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='acq_Date',
            new_name='acq_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='acq_Time',
        ),
        migrations.AddField(
            model_name='location',
            name='acq_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
