# Generated by Django 2.2.4 on 2019-10-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_village_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='village_subcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
