# Generated by Django 2.2.4 on 2019-09-03 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190903_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='acq_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
