# Generated by Django 2.2.4 on 2019-10-28 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dc_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoreport',
            name='created_on_ado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
