# Generated by Django 2.2.4 on 2019-09-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='ddo',
            new_name='dda',
        ),
    ]
