# Generated by Django 2.2.4 on 2019-10-31 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191028_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoreport',
            name='created_on_ado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
