# Generated by Django 2.2.4 on 2019-09-03 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190903_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ado', to='api.User'),
        ),
    ]
