# Generated by Django 2.2.4 on 2019-09-03 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190903_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='typeofChoice',
            new_name='status',
        ),
        migrations.AddField(
            model_name='location',
            name='csv_file',
            field=models.FileField(default='a.csv', upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
            preserve_default=False,
        ),
    ]
