# Generated by Django 2.2.4 on 2019-09-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190903_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='csv_file',
        ),
    ]
