# Generated by Django 2.2.4 on 2019-11-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191101_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoreport',
            name='challan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='adoreport',
            name='fir',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
