# Generated by Django 2.2.4 on 2019-09-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_location_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dda_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AlterField(
            model_name='location',
            name='dda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dda', to='api.User'),
        ),
    ]
