# Generated by Django 2.2.4 on 2019-09-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190904_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ddo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='ado',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'typeOfUser': 'ado'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ado', to='api.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dda_head',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeOfUser': 'dda'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
