# Generated by Django 2.2.4 on 2019-09-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190908_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('block_name', models.CharField(max_length=50)),
                ('village_name', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('kila_num', models.CharField(max_length=50)),
                ('murrabba_num', models.CharField(max_length=50)),
                ('incident_reason', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='ado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_ado', to='api.Ado'),
        ),
        migrations.AlterField(
            model_name='location',
            name='dda',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_dda', to='api.Dda'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdoReport')),
            ],
        ),
        migrations.AddField(
            model_name='adoreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
    ]
