# Generated by Django 2.2.4 on 2019-09-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_district_village'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoreport',
            old_name='block_name',
            new_name='farmer_code',
        ),
        migrations.RenameField(
            model_name='adoreport',
            old_name='district',
            new_name='ownership',
        ),
        migrations.RenameField(
            model_name='adoreport',
            old_name='name',
            new_name='village_code',
        ),
        migrations.RemoveField(
            model_name='ado',
            name='village_name',
        ),
        migrations.RemoveField(
            model_name='adoreport',
            name='village_name',
        ),
        migrations.AddField(
            model_name='ado',
            name='village',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ado_village', to='api.Village'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoreport',
            name='action',
            field=models.CharField(blank=True, choices=[('challan', 'Challan'), ('fir', 'FIR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dda',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dda_district', to='api.District'),
        ),
    ]
