# Generated by Django 2.2.4 on 2019-09-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190920_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='ado',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ado',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dda',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dda',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
