# Generated by Django 2.2.4 on 2019-09-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190920_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoreport',
            name='farmer_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoreport',
            name='father_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='action',
            field=models.CharField(choices=[('challan', 'Challan'), ('fir', 'FIR')], default='challan', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='farmer_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='kila_num',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='murrabba_num',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='village_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
