# Generated by Django 2.2.4 on 2019-09-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190921_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoreport',
            name='amount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
