# Generated by Django 2.2.4 on 2019-09-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190924_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ado',
            name='village',
        ),
        migrations.AddField(
            model_name='ado',
            name='village',
            field=models.ManyToManyField(related_name='ado_village', to='api.Village'),
        ),
    ]
