# Generated by Django 2.2.4 on 2019-09-27 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190925_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoreport',
            name='village',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_village', to='api.Village'),
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='village_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='block_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='village_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
