# Generated by Django 2.2.4 on 2019-09-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190927_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ado',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ado',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ado',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ado',
            name='village',
            field=models.ManyToManyField(blank=True, related_name='ado_village', to='api.Village'),
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='action',
            field=models.CharField(blank=True, choices=[('chalaan', 'Challan'), ('FIR', 'FIR')], default='FIR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='farmer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='kila_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adoreport',
            name='murrabba_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dda',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dda',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dda',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
