# Generated by Django 2.2.4 on 2019-09-28 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190928_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dda',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dda_district', to='api.District'),
        ),
    ]
